services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inceptionNetwork
    volumes:
      - wp:/var/www/html/
    env_file:
      - .env
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp:/var/www/html/
    networks:
      - inceptionNetwork

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inceptionNetwork
    volumes:
      - db:/var/lib/mysql/
    restart: always

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    volumes:
      - portainer:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    networks:
      - inceptionNetwork
    restart: always

  adminer:
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - inceptionNetwork
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zak/data/db/
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zak/data/wp/
  portainer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zak/data/portainer/

networks:
  inceptionNetwork:
    name: inceptionNetwork
    driver: bridge